# Generated by Django 4.2.2 on 2023-07-09 14:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('referal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_owner_name', models.CharField(max_length=20)),
                ('receipt_owner_phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Please Enter A Valid Egyptian Phone Number', regex='^01[0|1|2|5]{1}[0-9]{8}$')])),
                ('receipt_owner_referalcode', models.CharField(blank=True, max_length=5, null=True, unique=True)),
                ('receit_description', models.CharField(max_length=2000)),
                ('receipt_price', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ReferCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referCustomer_name', models.CharField(max_length=20)),
                ('referCustomer_phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Please Enter A Valid Egyptian Phone Number', regex='^01[0|1|2|5]{1}[0-9]{8}$')])),
                ('referCustomer_receipt', models.IntegerField(validators=[django.core.validators.MinValueValidator(1499)])),
                ('referCustomer_code', models.CharField(max_length=5, unique=True)),
                ('ReferCustomer_deals_totalprice', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='customer_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='customer_user_permissions', to='auth.permission'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('product_code', models.CharField(max_length=10)),
                ('product_description', models.CharField(max_length=2000)),
                ('product_price', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product_receit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referal.receipt')),
            ],
        ),
    ]
