# Generated by Django 4.2.2 on 2023-07-09 15:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referal', '0002_receipt_refercustomer_alter_customer_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='receipt_owner_referalcode',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='refercustomer',
            name='referCustomer_code',
            field=models.TextField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='refercustomer',
            name='referCustomer_receipt',
            field=models.IntegerField(max_length=7, validators=[django.core.validators.MinValueValidator(1500)]),
        ),
    ]
