# Generated by Django 4.2.2 on 2023-07-09 15:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referal', '0003_alter_receipt_receipt_owner_referalcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refercustomer',
            name='referCustomer_code',
            field=models.TextField(blank=True, max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='refercustomer',
            name='referCustomer_receipt',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1500)]),
        ),
    ]
