# Generated by Django 4.2.2 on 2023-07-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referal', '0004_alter_refercustomer_refercustomer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='receipt_owner_referalcode',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
