# Generated by Django 4.2.2 on 2023-07-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referal', '0005_alter_receipt_receipt_owner_referalcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='refercustomer',
            name='referCustomer_revenue',
            field=models.IntegerField(choices=[(10, 'Ten'), (5, 'Five')], default=10),
        ),
    ]
