# Generated by Django 4.2.2 on 2023-07-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referal', '0006_refercustomer_refercustomer_revenue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refercustomer',
            old_name='ReferCustomer_deals_totalprice',
            new_name='ReferCustomer_deals_totalpricefirst15days',
        ),
        migrations.AddField(
            model_name='refercustomer',
            name='ReferCustomer_deals_totalpricelast15days',
            field=models.IntegerField(default=0),
        ),
    ]
